version: "3"

services:
  frontend:
    build:
      context: ./../frontend
      dockerfile: ./../frontend/frontend.Dockerfile
    ports:
      - "3000:3000"

  api-gateway:
    build:
      context: ./../api-gateway
      dockerfile: ./../api-gateway/api-gateway.Dockerfile
    depends_on:
      - bin-manager
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  bin-manager:
    build:
      context: ./../bin-manager
      dockerfile: ./../bin-manager/bin-manager.Dockerfile
    depends_on:
      - mongo
    ports:
      - "65535:65535"
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    hostname: mongo_db
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bins
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
