// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script type=\"text/javascript\">\n  const navigateToNewBin = () => window.location.pathname = \"/new-bin\";\n  </script><div class=\"flex flex-col\"><div class=\"grid grid-cols-1 justify-items-center\"><div class=\"container bg-gray-400 h-84 rounded-md flex items-center\"><div class=\"text-gray-100 text-center sm:ml-20 sm:text-left my-20\"><p class=\"leading-none mb-2 text-5xl font-bold\">Test Your<br>Webhooks</p><p class=\"text-lg inline-block sm:block\">We create the bin. You direct the traffic</p><button class=\"mt-8 px-4 py-2 border-0 text-lg rounded\" style=\"background-color: #214f98;\" on:click=\"navigateToNewBin(this)\">Create Bin URL</button></div></div><div class=\"container grid grid-cols-3 gap-4 mt-4\"><div class=\"h3 text-lg font-semibold text-gray-500 mt-2\">1. Generate a Bin<p class=\"text-base font-normal text-gray-400\">We provide you with a URL which is the endpoint for an ephemeral bin. The data of all HTTP requests made to the endpoint is logged.</p></div><div class=\"h3 text-lg font-semibold text-gray-500 mt-2\">2. Direct Traffic to the Bin<p class=\"text-base font-normal text-gray-400\">You register the provided bin URL with the webhook service you're using or designing.</p></div><div class=\"h3 text-lg font-semibold text-gray-500 mt-2\">3. Review the Traffic<p class=\"text-base font-normal text-gray-400\">We provide you with an additional URL at which you can view the data of all HTTP requests made to your endpoint.</p></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
